In [102]:
# 1.Define a 1D, 2D, and 3D array with examples. 

import numpy as np
# 1D array
arr_1 = np.array([1,2,3,4,5])
print(f"1D array is : {arr_1}")

# 2D array
arr_2 = np.array([[1,2,3], [4,5,6]])
print(f"2D array is\n{arr_2}")

# 3D array
arr_3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(f"3D array is\n{arr_3}")

1D array is : [1 2 3 4 5]
2D array is
[[1 2 3]
 [4 5 6]]
3D array is
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [103]:
# 2.Explain the purpose of the reshape method in NumPy,
# Write a sample code to reshape a 1D array of size 12 into a 2D array with 3 rows and 4 columns.


# The reshape method in NumPy is used to change the shape of an array without altering its data,
# It allows you to rearrange the elements of an array into a new shape, specified by the dimensions
arr_1D = np.arange(1,13)
print(f"1D array is : {arr_1D}")
# Reshaping 1D array into 2D array
arr_2D = arr_1D.reshape(3,4)
print(f"2D array is\n {arr_2D}")

1D array is : [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D array is
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [104]:
# 3.Create a NumPy array with values from 1 to 20. Reshape it into a 4x5 matrix and find its mean, median, and standard deviation.
math_arr = np.arange(1,21)

# Reshaping into (4,5)
math_arr_reshaped = math_arr.reshape(4,5)
print(f"Reshaped array\n{math_arr_reshaped}")

# Finding its mean
mean_value = np.mean(math_arr_reshaped)
print("Mean value is : ",mean_value)

# Finding Median
median_value = np.median(math_arr_reshaped)
print("Median value is : ",median_value)

# Finding standard deviation
SD_value = np.std(math_arr_reshaped)
print(f"Standard deviation is {SD_value}")

Reshaped array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Mean value is :  10.5
Median value is :  10.5
Standard deviation is 5.766281297335398


In [105]:
# 4.Using the Pandas DataFrame below, answer the following:
import pandas as pd
data = {
    'col1': [10,40,70],
    'col2': [20,50,80],
    'col3': [30,60,90]
}
df = pd.DataFrame(data)
print("Data Frame is :\n",df)

# a) Select the first two rows and last two columns
result = df.iloc[[0,1],[1,2]]
print("first two rows and last two columns\n",result)

# b) Replace all values greater than 50 with Nan
df[df > 50] = np.nan
print("Replaced all values greater than 50 with Nan \n",df)

# c) Find and print the sum of each column
print("Data Frame is :\n",df)
column_sum = df.sum(axis=0)
print(f"Sum of each column are\n{column_sum}")

Data Frame is :
    col1  col2  col3
0    10    20    30
1    40    50    60
2    70    80    90
first two rows and last two columns
    col2  col3
0    20    30
1    50    60
Replaced all values greater than 50 with Nan 
    col1  col2  col3
0  10.0  20.0  30.0
1  40.0  50.0   NaN
2   NaN   NaN   NaN
Data Frame is :
    col1  col2  col3
0  10.0  20.0  30.0
1  40.0  50.0   NaN
2   NaN   NaN   NaN
Sum of each column are
col1    50.0
col2    70.0
col3    30.0
dtype: float64


In [106]:
# 5.Create a python program to perform the following
# Generate a NumPy array with values ranging from 1 to 90, stepping by 3.
gen_arr = np.arange(1,91,3).reshape(5,6)
print("Generated array is \n",gen_arr)

# Reshape it into a DataFrame with 10 rows and 3 columns
gen_arr_df_reshape = pd.DataFrame(gen_arr.reshape(10,3), columns= ['A','B','C'])
print(f"Reshaped into data frame with (10,3)\n{gen_arr_df_reshape}")

# Select and print the rows 2,4 and 6 along with columns 2 and 3 using iloc
gen_arr_df_reshape.iloc[[2,4,6],[1,2]]

Generated array is 
 [[ 1  4  7 10 13 16]
 [19 22 25 28 31 34]
 [37 40 43 46 49 52]
 [55 58 61 64 67 70]
 [73 76 79 82 85 88]]
Reshaped into data frame with (10,3)
    A   B   C
0   1   4   7
1  10  13  16
2  19  22  25
3  28  31  34
4  37  40  43
5  46  49  52
6  55  58  61
7  64  67  70
8  73  76  79
9  82  85  88


B   C
2  22  25
4  40  43
6  58  61

In [107]:
# 6.Handling Missing Values
# a.Create the following DataFrame

data = {
    'names': ['Steve', 'John', 'Richard', 'Sarah', 'Randy', 'Michael', 'Julie'],
    'age': [20, 22, 20, 21, 24, 23, 22],
    'gender': ['Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female'],
    'rank': [2, 1, 4, 5, 3, 7, 6]
}
df_1 = pd.DataFrame(data)
print("Data set is \n",df_1)

# b.Introduce missing values (NaN) in the age column for rows 2 to 5.
df_1.iloc[2:6, 1] = np.nan
print("missing values (NaN) in the age column\n",df_1)

# c.Demonstrate how to fill these missing values using:
# •	A constant value (e.g., 0)
# •	The mean of the column
# •	Print the modified DataFrame in each case.


# A constant value (e.g., 0)
constant_value = df_1.fillna(0)
print("Filled with missing value 0\n",constant_value)
# The mean of the column
mean_value = df_1['age'].mean()
print("The mean value of the age is : ",mean_value)

Data set is 
      names  age  gender  rank
0    Steve   20    Male     2
1     John   22    Male     1
2  Richard   20    Male     4
3    Sarah   21  Female     5
4    Randy   24    Male     3
5  Michael   23    Male     7
6    Julie   22  Female     6
missing values (NaN) in the age column
      names   age  gender  rank
0    Steve  20.0    Male     2
1     John  22.0    Male     1
2  Richard   NaN    Male     4
3    Sarah   NaN  Female     5
4    Randy   NaN    Male     3
5  Michael   NaN    Male     7
6    Julie  22.0  Female     6
Filled with missing value 0
      names   age  gender  rank
0    Steve  20.0    Male     2
1     John  22.0    Male     1
2  Richard   0.0    Male     4
3    Sarah   0.0  Female     5
4    Randy   0.0    Male     3
5  Michael   0.0    Male     7
6    Julie  22.0  Female     6
The mean value of the age is :  21.333333333333332


In [108]:
# 7.Interpolation of Missing Data:
# Explain the purpose of the interpolate() method in Pandas

#The interpolate() method in Pandas is used to fill missing values (NaN) in a dataset by estimating those values based on surrounding data points.
 
# Write Python code to apply interpolation to fill missing values in a DataFrame. 
print("Data set is\n",df_1)
print("After applying interpolate")
df_1.interpolate(method="linear")

Data set is
      names   age  gender  rank
0    Steve  20.0    Male     2
1     John  22.0    Male     1
2  Richard   NaN    Male     4
3    Sarah   NaN  Female     5
4    Randy   NaN    Male     3
5  Michael   NaN    Male     7
6    Julie  22.0  Female     6
After applying interpolate


C:\Users\SHAHZOR AHMED\AppData\Local\Temp\ipykernel_16968\1164579.py:9: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_1.interpolate(method="linear")


names   age  gender  rank
0    Steve  20.0    Male     2
1     John  22.0    Male     1
2  Richard  22.0    Male     4
3    Sarah  22.0  Female     5
4    Randy  22.0    Male     3
5  Michael  22.0    Male     7
6    Julie  22.0  Female     6

In [109]:
# 8.Dropping Rows with Missing Values:
# Create a DataFrame with missing values. 
data = {
    'Name': ['Steve', 'John', 'Richard', None, 'Julie'],
    'Age': [25, 30, np.nan, np.nan, 22],
    'Gender': ['Male', 'Male', 'Male', 'Female', None],
    'Rank': [1, 2, 3, None, None]
}
df_1 = pd.DataFrame(data)
print("My data set is \n",df_1)
# Write Python code to:
# a. Drop rows where any value is missing.
df_1.dropna()

My data set is 
       Name   Age  Gender  Rank
0    Steve  25.0    Male   1.0
1     John  30.0    Male   2.0
2  Richard   NaN    Male   3.0
3     None   NaN  Female   NaN
4    Julie  22.0    None   NaN


Name   Age Gender  Rank
0  Steve  25.0   Male   1.0
1   John  30.0   Male   2.0

In [110]:
# 9.Handling Duplicate Rows:
DF_obj = pd.DataFrame({
    'column 1': [1, 1, 2, 2, 3, 3, 3],
    'column 2': ['a', 'a', 'b', 'b', 'c', 'c', 'c'],
    'column 3': ['A', 'A', 'B', 'B', 'C', 'C', 'C']
})
print("My data set\n",DF_obj)
# a. Check for duplicate rows using the duplicated() method.
DF_obj.duplicated()
# b. Remove rows with duplicate values in column 3 using the drop_duplicates() method.
DF_obj.drop_duplicates(['column 3'])


My data set
    column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        C
6         3        c        C


column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C

In [111]:
# 10.Mean Imputation for Missing Values
# Create a DataFrame with missing values in the age column.
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
    'Age': [25, np.nan, 30, np.nan, 22],  # Missing values in 'Age'
    'Gender': ['Female', 'Male', 'Male', 'Male', 'Female'],
    'City': ['NY', 'LA', 'SF', 'NY', 'LA']
}
df_3 = pd.DataFrame(data)
print("My Data set is\n",df_3)
# Calculate the mean of the column and replace the missing values with this mean. Print the updated DataFrame.
mean_value_age = df_3['Age'].mean()
print("mean value of age is : ",mean_value_age)
df_3['Age'].fillna(mean_value_age, inplace= True)
df_3

My Data set is
       Name   Age  Gender City
0    Alice  25.0  Female   NY
1      Bob   NaN    Male   LA
2  Charlie  30.0    Male   SF
3    David   NaN    Male   NY
4     Emma  22.0  Female   LA
mean value of age is :  25.666666666666668


C:\Users\SHAHZOR AHMED\AppData\Local\Temp\ipykernel_16968\272479018.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_3['Age'].fillna(mean_value_age, inplace= True)


Name        Age  Gender City
0    Alice  25.000000  Female   NY
1      Bob  25.666667    Male   LA
2  Charlie  30.000000    Male   SF
3    David  25.666667    Male   NY
4     Emma  22.000000  Female   LA

11.	Concatenation of DataFrames 

In [112]:
# a.Create two DataFrames:
# DF_1 with values ranging from 0 to 35, reshaped into a 6x6 matrix.
DF_1 = pd.DataFrame(np.arange(0,36).reshape(6,6))
print("My Data Frame 1 is\n",DF_1)

# DF_2 with values ranging from 0 to 14, reshaped into a 5x3 matrix.
DF_2 = pd.DataFrame(np.arange(0,15).reshape(5,3))
print("My Data Frame 2 is\n",DF_2)

# Concatenate the DataFrames:
# i. Along columns.
concate_col = pd.concat([DF_1, DF_2], axis= 1)
print("Concatination along columns\n",concate_col)

My Data Frame 1 is
     0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35
My Data Frame 2 is
     0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14
Concatination along columns
     0   1   2   3   4   5     0     1     2
0   0   1   2   3   4   5   0.0   1.0   2.0
1   6   7   8   9  10  11   3.0   4.0   5.0
2  12  13  14  15  16  17   6.0   7.0   8.0
3  18  19  20  21  22  23   9.0  10.0  11.0
4  24  25  26  27  28  29  12.0  13.0  14.0
5  30  31  32  33  34  35   NaN   NaN   NaN


In [113]:
# ii. Along rows.
concate_row = pd.concat([DF_1, DF_2])
print("Concatination along rows\n",concate_row)

Concatination along rows
     0   1   2     3     4     5
0   0   1   2   3.0   4.0   5.0
1   6   7   8   9.0  10.0  11.0
2  12  13  14  15.0  16.0  17.0
3  18  19  20  21.0  22.0  23.0
4  24  25  26  27.0  28.0  29.0
5  30  31  32  33.0  34.0  35.0
0   0   1   2   NaN   NaN   NaN
1   3   4   5   NaN   NaN   NaN
2   6   7   8   NaN   NaN   NaN
3   9  10  11   NaN   NaN   NaN
4  12  13  14   NaN   NaN   NaN


In [114]:
# ii. Along rows with out repeating index.
concate_row = pd.concat([DF_1, DF_2], ignore_index= True)
print("Concatination along rows\n",concate_row)

Concatination along rows
      0   1   2     3     4     5
0    0   1   2   3.0   4.0   5.0
1    6   7   8   9.0  10.0  11.0
2   12  13  14  15.0  16.0  17.0
3   18  19  20  21.0  22.0  23.0
4   24  25  26  27.0  28.0  29.0
5   30  31  32  33.0  34.0  35.0
6    0   1   2   NaN   NaN   NaN
7    3   4   5   NaN   NaN   NaN
8    6   7   8   NaN   NaN   NaN
9    9  10  11   NaN   NaN   NaN
10  12  13  14   NaN   NaN   NaN


12.	Drop Operations 

In [115]:
# Using the DF_1 DataFrame:
# a. Drop rows with indices 0 and 2.
DF_1.drop([0,2], inplace = True)
print("After droping rows with indices 0 and 2\n",DF_1)
# b. Drop columns with indices 0 and 2.
DF_1.drop([0,2], axis = 1, inplace = True)
print("After droping columns with indices 0 and 2\n",DF_1)

After droping rows with indices 0 and 2
     0   1   2   3   4   5
1   6   7   8   9  10  11
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35
After droping columns with indices 0 and 2
     1   3   4   5
1   7   9  10  11
3  19  21  22  23
4  25  27  28  29
5  31  33  34  35


13.	GroupBy 

In [116]:
# Load the cars.csv dataset with columns:
address_of_cars_csv = "C:/Users/SHAHZOR AHMED/OneDrive/Desktop/Full Stack Academy/cars.csv"
cars = pd.read_csv(address_of_cars_csv)
print(cars)

             Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.

In [117]:
# Cars_name, mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb.
cars.columns = ['Cars_name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
print(cars)

              Cars_name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.

In [118]:
# b. Group the data by the column cyl.
grouped_data_cars_cyl = cars.groupby('cyl')
pd.DataFrame(grouped_data_cars_cyl)
# i.Calculate the mean of all numeric columns for each group.
grouped_data_cars_cyl.mean(numeric_only= True)


mpg        disp          hp      drat        wt       qsec  \
cyl                                                                     
4    26.663636  105.136364   82.636364  4.070909  2.285727  19.137273   
6    19.742857  183.314286  122.285714  3.585714  3.117143  17.977143   
8    15.100000  353.100000  209.214286  3.229286  3.999214  16.772143   

           vs        am      gear      carb  
cyl                                          
4    0.909091  0.727273  4.090909  1.545455  
6    0.571429  0.428571  3.857143  3.428571  
8    0.000000  0.142857  3.285714  3.500000

14.	Working with Series 

In [119]:
# a. Create a Series with values ranging from 0 to 5 and name it "Series column".
from pandas import Series
series_col = Series(np.arange(0,6))
series_col.name = "Series column"
print(series_col)
# b. Add this Series as a new column to DF_1.
joined_data = pd.DataFrame.join(DF_1, series_col)
print(joined_data)

0    0
1    1
2    2
3    3
4    4
5    5
Name: Series column, dtype: int32
    1   3   4   5  Series column
1   7   9  10  11              1
3  19  21  22  23              3
4  25  27  28  29              4
5  31  33  34  35              5
